# -*- coding: utf-8 -*-
"""Electric Vehicle Performance & Efficiency Analysis for Optimal Consumer Selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hP345xGyKGBynTwhSz7d3SqftMOuTGAB

# Project Title:

##Electric Vehicle Performance & Efficiency Analysis for Optimal Consumer Selection

# Domain:

##Automobile Analytics/Electric Vehicle Market / Consumer Decision Analytics

# Objective:

 * To analyze electric vehicle data using key metrics such as battery capacity, range, price, efficiency, and performance in order to compare vehicles across different seating categories and identify the top-performing models.

* The objective also includes evaluating trade-offs between cost, performance, and efficiency to support data-driven vehicle selection.

# Expected Outcome:

* Identify the best-performing electric vehicles based on efficiency, range, and overall performance.

* Compare vehicles using key metrics such as battery capacity, price, charging time, and safety rating.

* Provide data-driven insights to support better vehicle selection and decision-making.

#Dataset Information:

* Source: https://www.kaggle.com/datasets/srijan1upadhyay/ev-dataset

* Year / Timeline: 2024 to 2025

* Dataset Description:

    * The dataset consists of 36005 records of electric vehicles, where each row represents a unique EV model with detailed technical and commercial attributes. It includes key features such as battery capacity, driving range, charging time, price, performance metrics, and seating capacity.

    * The dataset also contains categorical and numerical variables covering manufacturer details, vehicle type, drive system.It supports segment-wise comparison and helps in identifying patterns and trends across different types of electric vehicles.

#Type of Analysis:

* Descriptive Analysis:

      * Price, range, efficiency summary
      * Battery and charging overview
      * Performance metrics distribution
      * Safety and warranty overview
      * Seat-wise vehicle distribution
      * Manufacturer-wise vehicle count

* Comparative Analysis:

      * Seat-wise vehicle comparison
      * Price and range comparison
      * Battery and efficiency comparison
      * Performance metrics comparison
      * Charging time comparison
      * Manufacturer performance comparison

# Stages for DA Project:

## Stage 1 – Problem Definition and Dataset Selection


###Business Problem:

* Electric vehicles differ in battery capacity, range, price, and performance, making it difficult to identify the best vehicle for different needs.

* Without proper analysis, users may select vehicles based on brand or assumptions instead of actual performance data.

* There is a need to compare EVs using multiple metrics to identify top-performing vehicles across different seating categories.

###Expected Outcome:

* Identify the best-performing electric vehicles based on efficiency, range, and overall performance.

* Compare vehicles using key metrics such as battery capacity, price, charging time, and safety rating.

* Provide data-driven insights to support better vehicle selection and decision-making.

###Data Selection,Source,Size,Features:

* Data Selection - Electric vehicle dataset, Detailed EV specifications, Multi-segment vehicle coverage from 2024 to 2025

* Source - https://www.google.com/url?q=https%3A%2F%2Fwww.kaggle.com%2Fdatasets%2Fsrijan1upadhyay%2Fev-dataset

* Features - Battery capacity, range, charging time, fast charging, price, efficiency score, acceleration, top speed, safety rating, warranty, seats, and manufacturer details

* Size
    * Rows - 36005 records
    * Columns - 22 features

* Manufacturer → String → EV Brand (Tesla, BYD, Etc.)
* Model → String → Model Name (Model S, Leaf, Etc.)
* Type → String → Vehicle Type (SUV, Sedan, Etc.)
* Drive_Type → String → Drivetrain: AWD, FWD, RWD
* Fuel_Type → String → Electric Or Hybrid
* Color → String → Exterior Color
* Battery_Kwh → Float → Battery Capacity In KWh
* Range_Km → Float → Estimated Range In Kilometers
* Charging_Time_Hr → Float → Time To Charge 0–100% In Hours
* Fast_Charging → Boolean → Supports Fast Charging (True/False)
* Release_Year → Int → Model Release Year
* Country → String → Available Country
* City → String → City Of Availability
* Seats → Int → Number Of Seats
* Price_Usd → Float → Price In USD
* Efficiency_Score → Float → Range Per KWh Efficiency Score
* Acceleration_0_100_Kmph → Float → 0–100 Km/H Acceleration Time (Seconds)
* Top_Speed_Kmph → Float → Top Speed In Km/H
* Warranty_Years → Int → Warranty Period In Years
* Cargo_Space_Liters → Float → Cargo/Trunk Capacity
* Safety_Rating → Float → Safety Rating (Out Of 5.0)
* Target_High_Efficiency → Binary → Target Label: 1 If Efficiency > 5.0, Else 0   

* Initial EDA:

    * head
    * info
    * describe
    * shape
    * null checks
    * duplicate check
"""

import pandas as pd
import numpy as np

df=pd.read_excel("https://raw.githubusercontent.com/Mithuvashini/Electric-Vehicle-Performance-Efficiency-Analysis-2024-2025/main/Electric%20Vehicle%20Performance%20%26%20Efficiency%20Analysis%20for%20Optimal%20Consumer%20Selection%20(%202024-2025).xlsx")
df

df1=pd.read_excel("https://raw.githubusercontent.com/Mithuvashini/Electric-Vehicle-Performance-Efficiency-Analysis-2024-2025/main/Electric%20Vehicle%20Performance%20%26%20Efficiency%20Analysis%20for%20Optimal%20Consumer%20Selection%20(%202024-2025).xlsx")
df2=pd.read_excel("https://raw.githubusercontent.com/Mithuvashini/Electric-Vehicle-Performance-Efficiency-Analysis-2024-2025/main/Electric%20Vehicle%20Performance%20%26%20Efficiency%20Analysis%20for%20Optimal%20Consumer%20Selection%20(%202024-2025).xlsx")
df3=pd.read_excel("https://raw.githubusercontent.com/Mithuvashini/Electric-Vehicle-Performance-Efficiency-Analysis-2024-2025/main/Electric%20Vehicle%20Performance%20%26%20Efficiency%20Analysis%20for%20Optimal%20Consumer%20Selection%20(%202024-2025).xlsx")

# First 5 rows
df.head()

# Last 5 rows
df.tail()

# Shape (rows, columns)
df.shape

# Total number of elements (rows × columns)
df.size

# Info (data types, non-null counts)
df.info()

# Count missing values per column
df.isnull().sum()

# Count duplicate rows
df.duplicated().sum()

# Unique values per column
df.nunique()

# Modify original dataframe (in-place)
df.drop_duplicates()

# Statistical summary (numerical columns)
df.describe()

"""## Stage 2 – Data Cleaning and Pre-processing

Handle missing values (impute or drop)

Handle duplicates

Convert data types if needed

### Handle missing values (impute or drop)
"""

# Count missing values per column
df.isnull().sum()

# To find negative Value in the dataframe
(df.select_dtypes(include='number') < 0).sum()

# To find and filter only negative Value in the dataframe
(df.select_dtypes(include='number') < 0).sum().loc[lambda x: x > 0]

#very less count of negative value so convert to null
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].mask(df[num_cols] < 0)

# Count missing values per column
df.isnull().sum()

# Understand group averages
df.groupby(['manufacturer', 'model', 'type', 'drive_type', 'fuel_type','color'])[['battery_kwh','range_km','charging_time_hr','price_usd','top_speed_kmph','warranty_years','top_speed_kmph','warranty_years']].mean().round(2)

# Fill missing values using group-wise mean
df['battery_kwh'] = df.groupby(['manufacturer', 'model', 'type', 'drive_type', 'fuel_type'])['battery_kwh'].transform(lambda x: x.fillna(x.mean()))
df['range_km'] = df.groupby(['manufacturer', 'model', 'type', 'drive_type', 'fuel_type'])['range_km'].transform(lambda x: x.fillna(x.mean()))
df['charging_time_hr'] = df.groupby(['manufacturer', 'model', 'type', 'drive_type', 'fuel_type'])['charging_time_hr'].transform(lambda x: x.fillna(x.mean()))
df['price_usd'] = df.groupby(['manufacturer', 'model', 'type', 'drive_type', 'fuel_type'])['price_usd'].transform(lambda x: x.fillna(x.mean()))
df['top_speed_kmph'] = df.groupby(['manufacturer', 'model', 'type', 'drive_type', 'fuel_type'])['top_speed_kmph'].transform(lambda x: x.fillna(x.mean()))
df['warranty_years'] = df.groupby(['manufacturer', 'model', 'type', 'drive_type', 'fuel_type'])['warranty_years'].transform(lambda x: x.fillna(x.mean()))

# Count missing values per column
df.isnull().sum()

"""### Convert data types if needed"""

cols = ['battery_kwh','range_km', 'charging_time_hr','efficiency_score','acceleration_0_100_kmph','top_speed_kmph','cargo_space_liters']
cols1=['price_usd','warranty_years']
# Decimal Point correction
df[cols] = df[cols].round(2)
# Data types change
df[cols1] = df[cols1].astype('int64')
df.head(10)

# create charging time in minutes from hours
df.insert(9,'charging_time_min',(df['charging_time_hr'] * 60).round(0).astype(int))
df

# Remove the column charging time in hrs
df = df.drop(columns=['charging_time_hr'], errors='ignore')
df

df.describe()

"""#Stage 3 – EDA and Visualizations

Univariate Analysis → distribution of single variables (countplot, histogram, boxplot)

Bivariate Analysis → relation between two variables (scatterplot, barplot, correlation heatmap)

Multivariate Analysis → relation among 3+ variables (pairplot, grouped analysis, pivot tables, advanced plots)

Interpretation MUST with every visualization

--- Focus on business story not just charts ---

Each chart must be in seperate cells.



"""

import matplotlib.pyplot as plt
import seaborn as sns

"""###Univariate Analysis → distribution of single variables (countplot, histogram, boxplot)

### CountPlot
"""

# Assign Variable
count = df['type'].value_counts().index

# Count Plot and Size of Chart
plt.figure(figsize=(10,6))
ax = sns.countplot(x='type', data=df, palette='pastel')

# Titles and labels
plt.title("Distribution of Car Type", fontsize=14, fontweight='bold')
plt.xlabel("Car Type", fontsize=12)
plt.ylabel("Count Of Car Realse", fontsize=12)
plt.xticks(rotation=45)

# show values on bars
for p in ax.patches:
    ax.text(p.get_x() + p.get_width()/2,p.get_height(),int(p.get_height()),ha='center')

# Show the Chart
plt.show()

"""###Interpretation of your above chart

### 📌 1. Explain the Chart

This chart is a Count Plot showing the distribution of different vehicle types in the dataset.

* Each bar represents a category in the type feature (Sedan, SUV, etc.)
* The height of each bar shows the number of records (count)
* Values on top indicate the exact frequency
* It is used for categorical univariate analysis

### 🔍 2. What is it saying?

The dataset contains multiple vehicle types such as Sedan, SUV, Hatchback, Coupe, etc.

* The counts of each category appear to be almost equal / uniformly distributed
* There is no single dominant category
* No category is extremely low → no rare class problem
* The dataset is well-balanced across vehicle types

👉 This means:

* No bias toward a specific vehicle type
* All categories are equally represented

### ⚙️ 3. What features you used?

* Feature: type
* Data type: Categorical
* Visualization: Count Plot (Seaborn)
* Analysis type: Univariate Analysis

### 🎯 4. What are you showing?

* Distribution of vehicle types
* Frequency of each category
* Comparison between categories
* Dataset balance across type

### Insight for the Chart

👉 The vehicle types are evenly distributed, with no single category dominating the dataset.

👉 This balanced distribution helps ensure unbiased analysis and better model performance across all types.

### Histogram
"""

# Assign Variable and Size of Chart
plt.figure(figsize=(7,5))
counts, bins, patches = plt.hist(df['price_usd'].dropna(),bins=10,color='skyblue',edgecolor='black')

# show values on bars
for i in range(len(counts)):
    plt.text((bins[i] + bins[i+1]) / 2,counts[i],int(counts[i]),ha='center',fontsize=11)

# Titles and labels
plt.title('Price Distribution',fontsize=14, fontweight='bold')
plt.xlabel('Price (USD)',fontsize=12)
plt.ylabel('Count',fontsize=12)

# Show the Chart
plt.show()

"""###Interpretation of your above chart

### 📌 1. Explain the Chart

This histogram shows the distribution of vehicle prices (price_usd).

* X-axis: Price ranges (in USD)
* Y-axis: Number of vehicles in each range
* Each bar represents how many vehicles fall within a specific price interval

### 🔍 2. What is it saying?

* The majority of vehicles are clustered between 24,000 and 36,000
* The highest concentration appears around 28,000 - 32,000
* Very few vehicles exist at the extreme low (<$10k) and high (>50k) ends
* The distribution is slightly right-skewed, meaning:
* More vehicles are in the low-to-mid range
* Fewer vehicles have very high prices

### ⚙️ 3. What features you used?

* Feature: price_usd
* Type: Numerical (continuous)
* Plot Type: Histogram
* Analysis Type: Univariate (single variable analysis)

### 🎯 4. What are you showing?

* Overall price distribution of vehicles
* The most common price range
* Presence of skewness and spread in pricing

### Insight for the Chart

👉 Most vehicles are concentrated in the mid-price range (~25k - 35k), indicating affordability for the majority of buyers.

👉 High-priced vehicles are relatively rare, suggesting limited representation of premium or luxury models in the dataset.

###  Boxplot
"""

# Assign Variable and Size of Chart
plt.figure(figsize=(7,5))

# Create Boxplot
box = plt.boxplot(df['efficiency_score'].dropna(),vert=True, patch_artist=True)

# Customize box color
for patch in box['boxes']:
    patch.set(facecolor='skyblue')

# Show median value on plot
median = df['efficiency_score'].median()
plt.text(1, median, f'Median: {round(median,2)}',horizontalalignment='center',fontsize=11,color='black')

# Titles and labels
plt.title('Efficiency Score Distribution', fontsize=14, fontweight='bold')
plt.ylabel('Efficiency Score', fontsize=12)

# Remove x-axis ticks (optional since only one box)
plt.xticks([])

# Show the Chart
plt.show()

"""### Interpretation of your above chart

### 📌 1. Explain the Chart

This boxplot shows the distribution of vehicle efficiency scores (efficiency_score).

* The box represents the middle 50% of values (Interquartile Range – IQR)
* The line inside the box shows the median efficiency score
* The whiskers show the spread of most data points
* Any points outside indicate potential outliers

### 🔍 2. What is it saying?

* Most vehicles have efficiency scores within a moderate range (middle 50%)
* The median indicates the typical efficiency level of vehicles
* If the box is slightly higher or lower → indicates skewness in efficiency
* Any outliers represent vehicles with exceptionally high or low efficiency

### ⚙️ 3. What features you used?

* Feature: efficiency_score
* Type: Numerical (continuous)
* Plot Type: Boxplot
* Analysis Type: Univariate

### 🎯 4. What are you showing?

* Spread and variability of efficiency scores
* Central tendency (median efficiency)
* Presence of outliers (unusual vehicles)
* Overall consistency of efficiency across vehicles

### Insight for the Chart

👉 Most vehicles have efficiency scores concentrated within a specific range, indicating relatively consistent performance across the dataset.

👉 A few outliers may represent highly efficient or less efficient vehicles, highlighting variation in technology or design.

## Bivariate Analysis → relation between two variables (scatterplot, barplot, correlation heatmap)

### Scatterplot
"""

# Size of Chart
plt.figure(figsize=(8,6))

# Create Scatter Plot
scatter = plt.scatter(df['battery_kwh'], df['range_km'],c=df['efficiency_score'], cmap='viridis',alpha=0.7)

# Add color bar (Efficiency legend)
plt.colorbar(scatter, label='Efficiency Score')

# Titles and Labels
plt.title('Battery vs Range (Colored by Efficiency)', fontsize=14, fontweight='bold')
plt.xlabel('Battery Capacity (kWh)', fontsize=12)
plt.ylabel('Range (km)', fontsize=12)

# Add grid for better readability
plt.grid(True, linestyle='--', alpha=0.5)

# Show the Chart
plt.show()

"""### Interpretation of the Chart

### 📌 1. Explain the Chart

This scatter plot shows the relationship between battery capacity (battery_kwh) and range (range_km), with color showing efficiency_score.

* Each dot represents a vehicle
* X-axis: Battery (0 to 150 kWh)
* Y-axis: Range (0 to 900 km)
* Color: Efficiency (dark = low, bright = high)

### 🔍 2. What is it saying?

There is a strong positive relationship

* Battery capacity ranges from ~0 to 150 kWh
* Driving range varies from ~0 to 900 km
* As battery increases from 50 → 100 kWh, range increases roughly from 300 → 650 km
* Range varies from ~500 km to ~700 km
* High efficiency (yellow/green):~700–850 km range at high battery
* Low efficiency (blue/purple):~550–650 km for same battery

### ⚙️ 3. What features you used?

* battery_kwh → Numerical (Independent)
* range_km → Numerical (Dependent)
* efficiency_score → Numerical (Color)
* Plot Type: Scatter Plot
* Analysis Type: Bivariate

### 🎯 4. What are you showing?

* Relationship between battery capacity and range
* Effect of efficiency on vehicle performance
* Variation in range for same battery size
* Distribution and spread of data points


### Insight for the Chart

👉 Battery capacity is the main factor affecting range.

👉 Efficiency plays a major secondary role, causing variation of up to 200 km for the same battery size.

👉 Vehicles with higher efficiency achieve greater range with the same battery, highlighting the importance of technology and design.

👉 Overall, the dataset shows a strong positive correlation with increasing variability at higher battery levels.

### Barplot
"""

# Group data
avg_charge = df.groupby('type')['charging_time_min'].mean().reset_index()

# Sort values
avg_charge = avg_charge.sort_values(by='charging_time_min', ascending=False)

# Set theme
sns.set_theme(style="whitegrid")

# Create figure
plt.figure(figsize=(11,6))

# Create bar plot
barplot = sns.barplot(
    x='type',
    y='charging_time_min',
    data=avg_charge,
    palette='Spectral'
)

# Add value labels (clean placement)
for i, row in avg_charge.iterrows():
    barplot.text(
        i,
        row['charging_time_min'] + 0.8,
        f"{row['charging_time_min']:.0f} min",
        ha='center',
        fontsize=11,
        fontweight='bold'
    )

# Titles and labels
plt.title('Average Charging Time by Vehicle Type', fontsize=18, fontweight='bold')
plt.xlabel('Vehicle Type', fontsize=13)
plt.ylabel('Charging Time (Minutes)', fontsize=13)

# Rotate x labels slightly
plt.xticks(rotation=20)

# Remove extra borders
sns.despine(left=True, bottom=True)

# Add subtle grid
plt.grid(axis='y', linestyle='--', alpha=0.4)

plt.tight_layout()
plt.show()

"""### Interpretation of the Chart

### 📌 1. Explain the Chart

This is a bar chart showing the average charging time across different vehicle types.

* X-axis: Vehicle Type (Coupe, Truck, Sedan, Hatchback, SUV, Crossover)
* Y-axis: Charging Time (in minutes)
* Each bar represents the average charging time for that vehicle category
Values are labeled on top of each bar

### 🔍 2. What is it saying?

* Charging times are almost identical across all vehicle types
* Range is very tight: 64 to 66 minutes
--- Coupe: ~66 min (highest)
--- Truck & Hatchback: ~64 min (lowest)
--- Others: ~65 min
* The difference is only 2 minutes, which is practically negligible

### ⚙️ 3. What features you used?

* type → Categorical (Independent variable)
* charging_time_hr (converted to minutes) → Numerical (Dependent variable)
* Plot Type: Bar Chart
* Analysis Type: Univariate (grouped comparison)

### 🎯 4. What are you showing?

* Comparison of average charging time by vehicle type
* Whether vehicle category impacts charging duration
* Uniformity or variation across categories

### Insight for the Chart

👉 Vehicle type has almost zero impact on charging time in this dataset.

👉 The variation is so small (±1–2 minutes) that it’s basically noise.

### Correlation heatmap
"""

# Selected columns
cols = [
    'battery_kwh',
    'range_km',
    'charging_time_min',
    'efficiency_score',
    'price_usd',
]

# Correlation matrix
corr = df[cols].corr()

# Plot
plt.figure(figsize=(10,8))
sns.heatmap(corr,annot=True,fmt='.2f',cmap='RdYlBu_r',center=0,square=True,linewidths=1,linecolor='white',cbar_kws={"shrink": 0.8})
plt.title('Correlation Heatmap (EV Key Metrics)', fontsize=16, fontweight='bold')

# Better label styling
plt.xticks(rotation=45, ha='right', fontsize=11)
plt.yticks(rotation=0, fontsize=11)

plt.tight_layout()
plt.show()

"""### Interpretation of the Chart

### 📌 1. Explain the Chart

This is a correlation heatmap showing relationships between key EV features:

* battery_kwh
* range_km
* charging_time_min
* efficiency_score
* price_usd
Each value ranges from -1 to +1:
Closer to 1 → strong positive relationship
Closer to 0 → no relationship

### 🔍 2. What is it saying?

✅ Strong Relationships (Core Insights)

* battery_kwh ↔ range_km → 0.91 (Very Strong)
👉 Vehicles with larger batteries have significantly higher driving range
* battery_kwh ↔ price_usd → 0.83 (Strong)
👉 Battery size is a major factor influencing vehicle price
range_km ↔ price_usd → 0.76 (Strong)
👉 Higher range vehicles are priced higher

⚠️ Moderate Relationships (Secondary Effects)

* battery_kwh ↔ charging_time_min → 0.43
* range_km ↔ charging_time_min → 0.40
👉 Larger batteries and higher range lead to moderately longer charging time
charging_time_min ↔ price_usd → 0.36
👉 More expensive vehicles tend to have slightly longer charging times (indirect effect via battery)

### ⚙️ 3. What features you used?

* battery_kwh → Numerical
* range_km → Numerical
* charging_time_min → Numerical
* efficiency_score → Numerical
* price_usd → Numerical
* Plot Type: Correlation Heatmap
* Analysis Type: Bivariate Analysis

### 🎯 4. What are you showing?

* Key drivers of vehicle price
* Dependency of range on battery capacity
* Relationship between charging time and battery size
* Relevance (or irrelevance) of efficiency score

### Insight for the Chart

👉 Battery capacity is the most influential feature
It directly impacts:

* range
* price
* charging time

👉 Range is strongly dependent on battery, not independent

👉 Price is driven mainly by battery and range, not efficiency

👉 Efficiency score is useless in this dataset

## Multivariate Analysis → relation among 3+ variables (pairplot, grouped analysis, pivot tables, advanced plots)

### Pairplot
"""

cols = [
    'battery_kwh',
    'range_km',
    'charging_time_min',
    'price_usd'
]

sns.set_style("whitegrid")

sns.pairplot(
    df[cols + ['target_high_efficiency']],
    hue='target_high_efficiency',   # adds meaningful color
    palette='Set2',                 # clean, distinct colors
    diag_kind='kde',
    corner=True,
    plot_kws={
        'alpha': 0.7,
        's': 60,
        'edgecolor': 'black'
    }
)

plt.suptitle('EV Pairplot (Colored by Efficiency)', y=1.02, fontsize=16)
plt.show()

"""### Interpretation of the Chart

### 📌 1. Explain the Chart

This is a pairplot of key EV features:

* battery_kwh
* range_km
* charging_time_min
* price_usd

With color representing:

0 → Low efficiency
1 → High efficiency

* Diagonal → distribution (KDE)
* Off-diagonal → relationships (scatter)

### 🔍 2. What is it saying?

✅ Strong Relationships (clear patterns)
🔹 Battery vs Range

👉 Strong upward linear trend

* As battery increases → range increases sharply
* Very tight pattern → strong dependency
🔹 Battery vs Price

👉 Clear positive relationship

* Higher battery → higher price
* Pricing is strongly driven by battery capacity
🔹 Range vs Price

👉 Strong positive trend

* Higher range vehicles are more expensive
Confirms range = market value driver

⚠️ Moderate Relationship
🔹 Charging Time vs Battery / Range

👉 Upward spread (but wider)

* Bigger battery → longer charging
* But scatter is wide → not perfectly consistent

### 🎯 4. What are you showing?

Core EV relationships:
* Battery → Range → Price
* Charging behavior vs battery
* Efficiency group distribution across features
* Density and spread of each variable

### Insight for the Chart

👉 Battery is the central driver

* Directly controls range
* Indirectly controls price

👉 Range is not independent

It’s just a result of battery

👉 Price is driven by performance (battery + range)

### Final Value Analysis
"""

def price_category(x):
    if x < 25000:
        return 'Economy'
    elif x <= 35000:
        return 'Standard'
    else:
        return 'Luxury'

df['price_category'] = df['price_usd'].apply(price_category)
df

df.to_csv("Electric Vehicle Performance & Efficiency Analysis for Optimal Consumer Selection.csv")

"""##Stage 4 – Documentation, Insights and Presentation
Show a dashboard aligning all the charts in powerbi

Summarize findings in plain English (what do the patterns mean)

Highlight 3–5 key insights (trends, anomalies, correlations)

Provide recommendations for business or decision-making

Explain the FINAL STORY WITH THE DASHBOARD

Create a PDF pasting your DASHBOARD, explaining all the above mentioned concepts and submit it
"""

# your stage 4 pdf Link

'''
step1 --> Create a docs that should have all the above mentioned
step2 --> Save it as "Stage4_doc"
Step3 --> Download it as PDF
step4 --> Upload the pdf in your drive
step5 --> Right click on your pdf in drive
step6 --> click share and change access into anyone with the link (Viewer)
step7 --> click copy link and paste it here...
You are done.
'''

"""## Future Enhancement

Use a larger or more recent dataset for deeper insights

Automate parts of the analysis with scripts or dashboards

Add advanced visualizations and interactive dashboards in Power BI or Tableau

Extend the analysis to predictive modeling for forecasting if needed

## Conclusion

From the analysis, we identified meaningful relationships and patterns in the dataset. The visualizations and insights highlight the main factors influencing the outcomes and provide a strong foundation for business decisions.
"""

